# Generated by Django 2.2 on 2021-07-28 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('decription', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email_id', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True)),
                ('decription', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projects', models.ManyToManyField(null=True, to='app.Project')),
            ],
        ),
    ]
