# Generated by Django 2.2 on 2021-07-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='decription',
            new_name='description',
        ),
    ]
