# Generated by Django 2.2 on 2021-07-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210728_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='projects',
        ),
    ]
